Created 'Activate Created Forecasts' test case and created few new methods and locators.
ayushpreenza07/SalesforceAutomation pull request #21
Opened 2024-04-17 10:24 UTC by neelimaboyina4018

Created 'Activate Created Forecasts' test case and created few new methods and locators.

2024-04-18 05:21 UTC, snaphray commented on src/test/java/step_definitions/salesforceDemo.java
> +        KeywordUtil.navigateToUrl("https://testingxperts17-dev-ed.develop.my.salesforce.com/");//neelima SF URL
Please don't remove the line to navigate to the url, just comment it while testing and while committing just comment your line and uncomment the original one

2024-04-18 05:22 UTC, snaphray commented on src/test/java/SalesforceModules/ForecastingModule.java
> +    public static void validateForecastSettingsPageShouldBeLoaded() throws InterruptedException {
Please add proper comments for each method

2024-04-18 05:22 UTC, snaphray requested changes
Please check review comments

2024-04-18 10:44 UTC, neelimaboyina4018 commented
Hi @snaphray, Updated files as per the review comments.

2024-04-23 07:24 UTC, snaphray approved these changes
Code looks fine now

2024-04-23 07:24 UTC, merged